on:
  push:
    branches:    
      - master
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        env:
          MY_VAR: Hello God!
        run: |
          echo $MY_VAR
  server:
    needs: job1
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Make executable
        run: chmod +x ip_proxy.sh
      - name: Run a script
        run: ./ip_proxy.sh

